[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["node scripts/set-env.js && ng build --configuration production"]

[start]
cmd = "serve -s dist/chat-frontend/browser -l $PORT"
